const part2Lib1 = 'part2Lib'
// Generated by https://quicktype.io

export interface TopLevel {
    scripts: Script[];
}

export interface Script {
    clientId: string;
    uri: string;
    contentLength: number;
}

https://example.com/comments/1

